[package]
name = "evenOrOdd"
version = "0.1.0"
authors = ["s00kee <ceewaiohey@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
